tasklists:

  Concurrency:
    tags: []
    doc: https://teradata.sharepoint.com/teams/ServicessAnalyticsHub/COA/Documentation/SitePages/Metric_Concurrency.aspx

  DBC Column Summary:
    tags: []
    doc: https://teradata.sharepoint.com/teams/ServicessAnalyticsHub/COA/Documentation/SitePages/Metric_DBC_Column_Summary.aspx

  DBC Constraint:
    tags: []
    doc: https://teradata.sharepoint.com/teams/ServicessAnalyticsHub/COA/Documentation/SitePages/Metric_DBC_Constraint.aspx

  DBC Indices by Database:
    tags: []
    doc: https://teradata.sharepoint.com/teams/ServicessAnalyticsHub/COA/Documentation/SitePages/Metric_DBC_Indices_by_Database.aspx

  DBC Object Count:
    tags: []
    doc: https://teradata.sharepoint.com/teams/ServicessAnalyticsHub/COA/Documentation/SitePages/Metric_DBC_Object_Count.aspx

  System CPU by Day:
    tags: []
    doc: https://teradata.sharepoint.com/teams/ServicessAnalyticsHub/COA/Documentation/SitePages/Metric_System_CPU_by_Day.aspx

  Transfer Bytes In-Out:
    tags: []
    doc: https://teradata.sharepoint.com/teams/ServicessAnalyticsHub/COA/Documentation/SitePages/Metric_Transfer_Bytes_In_Out.aspx
